name: Test-CI

on:
    push:
        branches:
            - feature

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Pages
              run: echo "hello"
    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: test
          run: echo "test--completed"
    deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: test
          run: echo "deploy--completed"
